"""Add member model

Revision ID: 650a7b20030f
Revises: a2d0ceba1750
Create Date: 2023-01-22 11:49:09.757312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650a7b20030f'
down_revision = 'a2d0ceba1750'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('avatar', sa.String(length=256), nullable=False),
    sa.Column('avatar_thumbnail', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    # ### end Alembic commands ###
